### PR TITLE
Implement enhanced transaction parameters

### PR DESCRIPTION
**Pull request by modemaizer**
@maartenba could you please include these changes too?
I fixed products parsing and implemented an Refund tracking here.

### CODE REVIEW

**Comment by maartenba** [comment]
Could you rebase those on `mb-netcore2` branch? That will very soon become the new master.

**Comment by modemaizer** [comment]
> Could you rebase those on `mb-netcore2` branch? That will very soon become the new master.

It is PR to `mb-netcore2` branch. Do I still need to rebase it?

**Comment by maartenba** [comment]
Yeah looks like some conflicting changes. Maybe checkout that branch and cherry-pick your last two commits in this PR on it?

**Comment by modemaizer** [comment]
Ok, I'll do it soon

**Comment by maartenba** [comment]
With your other PR merged now, is this one still relevant?

**Comment by modemaizer** [comment]
No, it isn't relevant yet.
Thank you!

**Comment by maartenba** [comment]
Thank YOU! Pushing preview package to NuGet in a bit.

**Pull request closed without merging**
