### PR TITLE
Optional proxy settings.

### PR DESCRIPTION
**Pull request by taskinkemal**
When provided, the HTTP client will use the proxy settings (Host and Port) to send data.

### CODE REVIEW

**Comment by maartenba** [comment]
Wondering: would it be better if there was a clalback to create the `HttpClient` / pass in a handler?
Right now this code allows proxy settings, but then what if the proxy requires authentication -> would need another overload.

I'm leaning more towards allowing a method where the `HttpClient` can be created with a custom `HttpClientHandler`?

**Comment by taskinkemal** [comment]
Hi,

Yes, a general solution would be better but I didn't want to make the change bigger. I cannot commit to more refactoring at the moment. Please feel free to do however you'd like. Maybe if I need to do further changes I can include this in the pull request.

Cheers,
Kemal

**Comment by maartenba** [comment]
Are you okay with me leaving this PR open for a bit then? Low on bandwidth myself, and I'd rather get the handler-based change in.

**Comment by taskinkemal** [comment]
Sure.

**Comment by maartenba** [comment]
Made some changes to your PR and just accepted it in. You are now able to pass in a custom handler (and set proxy that way). Thanks again for your contribution and suggestion!

**Pull request merged**
