### PR TITLE
Updated all projects to .Net Standard 2.0

### PR DESCRIPTION
**Pull request by adamhwang**
PCL -> .Net Standard 2.0
.Net Framework 4.5 -> .Net Framework 4.6.1 / .Net Standard 2.0

### CODE REVIEW

**Comment by maartenba** [comment]
Thanks @adamhwang !

**Comment by maartenba** [comment]
@adamhwang Mind checking https://github.com/maartenba/GoogleAnalyticsTracker/pull/154 and see if that helps your case as well?

**Comment by adamhwang** [comment]
@maartenba Thanks for that, but my use case is a bit different as I'm only running analytics on one particular controller, so I implemented the SimpleTracker manually outside of the provided service registrations

**Comment by maartenba** [comment]
Cool :-) Thanks again!

**Pull request merged**
