### PR TITLE
Added support for ContentExperiment

### PR DESCRIPTION
**Pull request by ysasaki1985**
Added support for sending content experiment related info

### CODE REVIEW

**Comment by gandarez** [comment]
I'll look into this tonight

**Comment by maartenba** [comment]
Thanks @gandarez and @ysasaki1985 !

**Comment by maartenba** [comment]
@gandaraz are we good to merge this in?

**Comment by gandarez** [comment]
@maartenba I didn't have time to analyze it. I'll do it today and will come back with details.

**Comment by gandarez** [comment]
@ysasaki1985 
After reviewed the code I did few changes and commited to my repo under this commit
https://github.com/gandarez/GoogleAnalyticsTracker/commit/e69a4f96c350a457bf5c6103f5a815e03e4fb0dd

The content experiments is supported by all hit types, so I created a constructor into ContentExperiments.cs to get which hit type is being set.

**Comment by maartenba** [comment]
Can we merge it into master on this repo?

**Comment by gandarez** [comment]
@maartenba I did a PR right now. Feel free to merge it or delegate it to me.

**Comment by maartenba** [comment]
Please merge (and remove this one here)

**Comment by gandarez** [comment]
Closed as implemented in #90

**Comment by maartenba** [comment]
Thanks, pushing to NuGet right now.

**Comment by ysasaki1985** [comment]
Great, thanks guys!

**Pull request closed without merging**
