### PR TITLE
Xamarin Support and changed paject to PCL

### PR DESCRIPTION
**Pull request by scinfu**
Simple project was not compatible with Xamarin , so I changes the configuration to PCL and use TargetFrameworkProfile Profile111.

If you need more changes let me know.

### CODE REVIEW

**Comment by gandarez** [comment]
I think the Simple project should be renamed to Xamarin

**Comment by maartenba** [comment]
It can do more than just Xamarin :-)

**Comment by scinfu** [comment]
Maybe also a better implementation.

**Comment by scinfu** [comment]
When will be available in Nuget ?

**Comment by maartenba** [comment]
It is as prerelease now

**Pull request merged**
