### PR TITLE
Implemented Google Analytics Measurement Protocol

### PR DESCRIPTION
**Pull request by gandarez**
Hi Guys!

I've done a hard job to implement the new Measurement Protocol from Google Analytics. It includes a new Core and Web Api 2.

### CODE REVIEW

**Comment by dsghi** [comment]
Nice!

**Comment by maartenba** [comment]
Thanks @gandarez! Would you mind replaying these changes onto the old Core? I think we can safely remove the old approach and use the Measurement Protocol instead.No need for separate projects imho.

**Comment by gandarez** [comment]
Hi @maartenba! Yup I can do it. The single problem I see is that the old core has to be modified a lot. What I can do is to update all projects and submit a pull request to be analyzed by you. What do you think about it?

**Comment by maartenba** [comment]
Sounds very good! We can always rebrand it as GoogleAnalyticsTracker 3, so don't worry too much about breaking changes.

**Comment by gandarez** [comment]
@maartenba cool! I'll make some efforts this weekend to get it updated ASAP.

**Comment by maartenba** [comment]
@gandarez so how's this going? :)

**Comment by gandarez** [comment]
@maartenba There's a problem related to portable classes. I can't simply migrate my code to a portable class because I'm using couple features from non-portable. I think the only one project which needs to use portable class is WP8. Do you mind exclude it from migration?

**Comment by maartenba** [comment]
No worries, feel free to exclude it. I will see afterwards if I can port WP8.

**Comment by gandarez** [comment]
Hi @maartenba I finished porting code to new measurement protocol. Unfotunately Windows Phone 8 and Windows RT were excluded because the library core can't be(at this time) migrated to Portable version.

**Comment by maartenba** [comment]
Just to keep you posted: I'm nearly finished merging. I'm making it a PCL again so we can use Windows Phone etc. as well.

**Comment by gandarez** [comment]
@maartenba let me know if you need support.

**Comment by maartenba** [comment]
Looks good so far, just pushed an alpha version to NuGet (4.0.0-alpha00000 for all packages)

Much appreciated work, @gandarez ! Really happy with this.

**Comment by maartenba** [comment]
Did you have a chance to play with the new NuGet package?

**Comment by gandarez** [comment]
@maartenba not yet. Will try it out and post results in this forum.

**Pull request merged**
