### PR TITLE
Remove ReferralUrl, Hostname, Language, CharacterSet

### LINKED ISSUE #126: GeneralParameters.ReferralUrl not used
The `GeneralParameters.ReferralUrl` is not used, since the `parameters` in the `BaseTracker.RequestUrlAsync` contains properties with the `BeaconAttribute` only.

Note: `TrackerBase.CharacterSet` and `Language` seems unused, too.

### PR DESCRIPTION
**Pull request by xmedeko**
Fix #126
I have removed the Hostname used in the SimpleTracker to keep the SimpleTracker simple. Anyone may use AmendParameter to set DosumentHostname if they like.

### CODE REVIEW

**Comment by maartenba** [comment]
To be honest, I'd like to keep these - SimpleTracker should indeed be simple but setting things like language is something any app may want to do. Thoughts?

**Comment by xmedeko** [comment]
`UserLanguage` is interesting just for the multi user language apps.
`DocumentHostname` - I do not see any use case for the common console, WPF, WinForms apps.
There are more params the users may like to set, e.g. I need to set `ApplicationVersion`. IMHO it's not good to put everything which may be usable to the `SimpleTracker`, better to provide a simple way a user may add what she need.

**Comment by maartenba** [comment]
Agree on that. One thing: doing this would mean going from v4 to v5 (as it's breaking changes in SemVer world). Can we maybe mark these properties as deprecated for now and remove them in the next version? Finding a major version bump a bit crazy for this.

**Comment by xmedeko** [comment]
Ok, but do not know much about which changes break the SemVer MAJOR. Are they properties, in the `TrackerBase` or in the `IGeneralParameters`? Or do you need to return back the Tracker constructor `trackerDomain`? Note, some incompatible changes has been done by #132, too.

**Comment by maartenba** [comment]
Whenever it's backwards-breaking, a SemVer major update is required in theory. #132 indeed is one too, hmmm...

**Comment by xmedeko** [comment]
Yep, and you have be warned in #132: "but that would break the backward compatibility" 😉

**Comment by maartenba** [comment]
In that case: thanks man! :-) Will bump the version on release...

**Pull request merged**
