### PR TITLE
Remove GoogleBoolean and use bool

### PR DESCRIPTION
**Pull request by xmedeko**
Or, maybe remove `GoogleBoolean` and change it for `bool`? The only change to use `bool` is `TrackerBase.GetParametersDictionary`.

### CODE REVIEW

**Comment by xmedeko** [comment]
Me too, but that would break the backward compatibility. Should change this PR to remove `GoogleBoolean`?

**Comment by gandarez** [comment]
The boolean should be informe as "1" or "0" according to documentation. So I did some refactoring and the method `GetParametersDictionary` must be changed to treat framework boolean.

Adding this line to the method we guarantee that the GoogleBoolean could be safely removed 

```C#
else if (p.PropertyType == typeof(bool) || Nullable.GetUnderlyingType(p.PropertyType) != null)
{
	var val = p.GetMethod.Invoke(parameters, null);
	value = val == null ? "0" : (bool)val ? "1" : "0";
}
```

**Comment by xmedeko** [comment]
What about just a `value` type check `if (value.GetType() == typeof(bool))` ?

**Comment by gandarez** [comment]
Because few parameters are not requireds.

**Comment by xmedeko** [comment]
Yep, with the code around it would look like:
```c#
if (value == null)
    continue;
if (value is bool)
    value = ((bool)value) ? "1" : "0";
beaconList.Add(attr.Name, value.ToString());
```

**Comment by gandarez** [comment]
@xmedeko 

```C#
else if (p.PropertyType == typeof(bool) || Nullable.GetUnderlyingType(p.PropertyType) != null)
{
    var val = p.GetMethod.Invoke(parameters, null);
    if (val == null) continue;
    value = (bool)val ? "1" : "0";
}
```

**Comment by xmedeko** [comment]
@gandarez But why to check `PropertyType`, why simple `value is bool` is not enough?

**Comment by gandarez** [comment]
@xmedeko Here are all the GoogleBooleans we've set up. All those are optional according to the documentation. So if we make those booleans non-nullable it means that the state will be always false when them aren't set up.

- `IsFatal` [documentation](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#exf)
- `AnonymizeIp` [documentation](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#aip)
- `NonInteractionHit` [documentation](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#ni)
- `JavaEnabled` - [documentation](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#je)

**Comment by xmedeko** [comment]
There's no reason to make them non-nullable, then may be nullable `bool?`.

**Comment by gandarez** [comment]
Yes it should be nullable `bool?`

**Comment by xmedeko** [comment]
I see just a little problem with `IsFatal`, currently, it is not nullable and default value is 0 (false). By the spec, it's optional and default value is 1 (true). So, it should be `bool?` to strictly match the spec., but it would break backward compatibility. So I better change to non-nullable `bool`.

**Comment by gandarez** [comment]
You'reright. Change the class `ExceptionTracking` and initialize the default value of property `IsFatal` to true as follow:

```C#
public class ExceptionTracking : GeneralParameters, IExceptionParameters
{
    private GoogleBoolean _isFatal = GoogleBoolean.True;
    
    public virtual GoogleBoolean IsFatal
    {
        get { return _isFatal; }
        set { _isFatal = value; }
    }
}
```

**Comment by xmedeko** [comment]
There's no need to initialize it to `true` - if the nullable type is used, then `null` means `1` for `IsFatal`. We need to to set it to `false` if the nullable type and backward compatibility is required.
1. match the spec, break compatibility, default to `null` - `1`:
```c#
public bool? IsFatal { get; set; }
```
2. match the spec, keep compatibility
```c#
public ExceptionTracking()
{
    IsFatal = false;
}

public bool? IsFatal { get; set; }
```
3. not strictly by spec. keep compatibility
```c#
public bool IsFatal { get; set; }
```

The question is, wheter to keep the backward compatibility, if the change to `bool` break it anyway. So maybe I would to the 1.

**Comment by gandarez** [comment]
I go with item 1 too.

**Comment by xmedeko** [comment]
@gandarez @maartenba I've changed the code to reflect the discussion.

**Pull request merged**
