### PR TITLE
Generic PCL

### PR DESCRIPTION
**Pull request by scinfu**
This is a generic PCL compatible with Xamarin , Windows form or whatever c# .

### CODE REVIEW

**Comment by scinfu** [comment]
I do not make any changes to `GoogleAnalytics.Core` , I create a new generic PCL to use it both on Xamarin and Windows.

**Comment by maartenba** [comment]
That's the thing: how would you feel about just updating GoogleAnalytics.Core and make it a generic PCL instead of requiring another project?

**Comment by scinfu** [comment]
It can be a better approach in my opinion . Making a shared class `Tracker : TrackerBase`?

**Comment by maartenba** [comment]
There's https://github.com/maartenba/GoogleAnalyticsTracker/tree/master/GoogleAnalyticsTracker.Simple for that :-) Perhaps it's possible to make a generic PCL from that one instead?

**Comment by scinfu** [comment]
Yes , this pcl was the base of my Generic , the only thing that is not compatible with Xamarin is [SimpleTrackerEnvironment.cs](https://github.com/maartenba/GoogleAnalyticsTracker/blob/master/GoogleAnalyticsTracker.Simple/SimpleTrackerEnvironment.cs).
Have you preferences on the implementation?

**Comment by maartenba** [comment]
I'm ok with replacing it with the version you have in this PR.

**Comment by scinfu** [comment]
Ok , let me change it and i will make a new pull request.

**Comment by maartenba** [comment]
Thanks @scinfu ! That is much appreciated! Will close this one for now then.

**Pull request closed without merging**
